### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Magicloud** [7sDream/which_fonts_support#1]
```
Font(s) support the char [ ⫴ ](10996, U+002af4, e2abb4):
Traceback (most recent call last):
  File "./which_fonts_support.py", line 192, in <module>
    __main()
  File "./which_fonts_support.py", line 166, in __main
    max_width = max(map(wcwidth.wcswidth, typefaces))
ValueError: max() arg is an empty sequence
```

**Comment by 7sDream** [comment]
That means there is no font support the character. But the exception is not expected. Fixed in version v1.1.1 .
